# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Make envfile
      uses: tezz94820/DK_ACADEMY_SERVER@v1.0
      with:
        envkey_PORT: ${{ secrets.PORT }}
        envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
        envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
        envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
        envkey_JWT_LIFETIME: ${{ secrets.JWT_LIFETIME }}
        envkey_FAST2SMS_API_KEY: ${{ secrets.FAST2SMS_API_KEY }}
        envkey_CRYPT_PASSWORD: ${{ secrets.CRYPT_PASSWORD }}
        envkey_CRYPT_IV: ${{ secrets.CRYPT_IV }}
        file_name: .env
        fail_on_empty: false
        sort_keys: false
    - run: npm ci
    - run: npm run build --if-present
    - run: pm2 restart pm2.config.js
